# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://ldd110.github.io
date_format: "ordinal"
title: LiDanDan's Blog
subtitle: "多看！多读！多思！多写！不再沉默"
description: "LiDanDan的个人博客"
keywords: ldadan, blog
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ldd110
#organization: Sogou, Inc.
#organization_url: https://www.sogou.com
github_username: ldd110 
location: Beijing, China
email: danganlidandan@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
#subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ldd110/ldd110.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus
comments_provider: disqus
# !!!重要!!! 请修改下面这些用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
disqus_username: FSilence

gitalk:
        owner:FSilence
        clientID:test
        clientSecret:test
# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
